In [1]:
import pandas as pd
import numpy as np

In [2]:
df_songs = pd.read_csv('./data/spotify_songs_analysis.csv')

In [3]:
df_songs.shape

(183204, 31)

In [4]:
df_songs.head()

user_id             song_id  play_count  \
0  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOAKIMP12A8C130995           1   
1  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBFOVM12A58A7D494           1   
2  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBVFZR12A6D4F8AE3           1   
3  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBXALG12A8C13C108           1   
4  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SODACBL12A8C13C273           1   

                           song_title           artist_id      artist_name  \
0                            The Cove  ARC8CQZ1187B98DECA     Jack Johnson   
1     Riot Radio (Soundtrack Version)  ARI4V0E1187B9B6FC2     The Dead 60s   
2  Ears To The Ground (Album Version)  ARMS97V1187B99DD98       Josh Rouse   
3          Food Chain (Album Version)  ARG3I891187FB3A391  Eric Hutchinson   
4                        Learn To Fly  AR6XPWV1187B9ADAEB     Foo Fighters   

  song_prefix                            spotify_id  \
0          AK  spotify:track:4nuY11Vo1Yd5xMHhLfDKe9   
1          BF  spotify:track:2HPwuvT6HKngPSynOCi6Lb   
2          BV  spotify:track:5WjXULJvSlMxuies9diz1Q   
3          BX  spotify:track:1bqi9YEdZweX9H6JuSQ6Qw   
4          DA  spotify:track:4tjBDR8r3kxBXxQPeRTQgu   

                                       audio_feature  acousticness  ...   \
0  [{u'track_href': u'https://api.spotify.com/v1/...      0.656000  ...    
1  [{u'track_href': u'https://api.spotify.com/v1/...      0.000111  ...    
2  [{u'track_href': u'https://api.spotify.com/v1/...      0.172000  ...    
3  [{u'track_href': u'https://api.spotify.com/v1/...      0.410000  ...    
4  [{u'track_href': u'https://api.spotify.com/v1/...      0.000016  ...    

     tempo  time_signature                                         track_href  \
0  123.685             4.0  https://api.spotify.com/v1/tracks/4nuY11Vo1Yd5...   
1  143.948             4.0  https://api.spotify.com/v1/tracks/2HPwuvT6HKng...   
2  123.195             4.0  https://api.spotify.com/v1/tracks/5WjXULJvSlMx...   
3  112.492             4.0  https://api.spotify.com/v1/tracks/1bqi9YEdZweX...   
4  135.994             4.0  https://api.spotify.com/v1/tracks/4tjBDR8r3kxB...   

             type                                   uri  valence  \
0  audio_features  spotify:track:4nuY11Vo1Yd5xMHhLfDKe9    0.387   
1  audio_features  spotify:track:2HPwuvT6HKngPSynOCi6Lb    0.839   
2  audio_features  spotify:track:5WjXULJvSlMxuies9diz1Q    0.417   
3  audio_features  spotify:track:1bqi9YEdZweX9H6JuSQ6Qw    0.601   
4  audio_features  spotify:track:4tjBDR8r3kxBXxQPeRTQgu    0.505   

                                             release  artist_familiarity  \
0                                 Thicker Than Water            0.832012   
1  Nick & Norah's Infinite Playlist - Original Mo...            0.650281   
2                              Under Cold Blue Stars            0.675339   
3                                   Sounds Like This            0.806208   
4                      There Is Nothing Left To Lose            0.839275   

   artist_hotttnesss  year  
0           0.677482     0  
1           0.451749     0  
2           0.499641  2002  
3           0.498077  2008  
4           0.550762  1999  

[5 rows x 31 columns]

In [5]:
df_songs.columns

Index([u'user_id', u'song_id', u'play_count', u'song_title', u'artist_id',
       u'artist_name', u'song_prefix', u'spotify_id', u'audio_feature',
       u'acousticness', u'analysis_url', u'danceability', u'duration_ms',
       u'energy', u'id', u'instrumentalness', u'key', u'liveness', u'loudness',
       u'mode', u'speechiness', u'tempo', u'time_signature', u'track_href',
       u'type', u'uri', u'valence', u'release', u'artist_familiarity',
       u'artist_hotttnesss', u'year'],
      dtype='object')

In [6]:
num_features = ['acousticness','danceability','duration_ms','energy','instrumentalness','liveness', \
                'loudness','speechiness','tempo','time_signature','valence','artist_familiarity', \
                'artist_hotttnesss']
cat_features = ['key','mode','year']

In [7]:
print df_songs[num_features].describe()

        acousticness   danceability   duration_ms         energy  \
count  183203.000000  183161.000000  1.832040e+05  183203.000000   
mean        0.277152       0.526918  2.401994e+05       0.638811   
std         0.322849       0.176007  1.004854e+05       0.254961   
min         0.000000       0.055500  4.037000e+03       0.000020   
25%         0.006950       0.403000  1.844930e+05       0.455000   
50%         0.112000       0.533000  2.283070e+05       0.680000   
75%         0.519000       0.656000  2.784000e+05       0.860000   
max         0.996000       0.997000  3.035280e+06       1.000000   

       instrumentalness       liveness       loudness    speechiness  \
count     183203.000000  183202.000000  183204.000000  183161.000000   
mean           0.186597       0.215107      -9.047922       0.084492   
std            0.318713       0.191067       4.709803       0.111716   
min            0.000000       0.008580     -54.909000       0.021900   
25%            0.000002    

### K-Means clustering

In [8]:
from sklearn.cluster import KMeans

In [19]:
from sklearn.metrics import silhouette_score

In [9]:
X = df_songs[num_features].fillna(0.)

In [15]:
kmeans = KMeans(n_clusters=10, random_state=0).fit(X)

In [16]:
X.shape, kmeans.labels_.shape

((183204, 13), (183204,))

In [ ]:
#cluster_labels = kmeans.labels_

#silhouette_avg = silhouette_score(X, cluster_labels, metric='euclidean')
#print("For n_clusters =", 3,
#        "The average silhouette_score is :", silhouette_avg)

In [21]:
np.bincount(kmeans.labels_)

array([45875,  6419, 28823, 14211,    60,   379, 46120, 29101, 10443,  1773])

### Hierarchical Clustering

In [8]:
from sklearn.cluster import AgglomerativeClustering
from sklearn.neighbors import kneighbors_graph

In [43]:
# Create a graph capturing local connectivity. Larger number of neighbors
# will give more homogeneous clusters to the cost of computation
# time. A very large number of neighbors gives more evenly distributed
# cluster sizes, but may not impose the local manifold structure of
# the data
knn_graph = kneighbors_graph(X, 30, include_self=False)

In [44]:
knn_graph

<183204x183204 sparse matrix of type '<type 'numpy.float64'>'
	with 5496120 stored elements in Compressed Sparse Row format>

In [45]:
knn_graph[90:100,90:100].toarray()

array([[ 0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [11]:
h_clustering = AgglomerativeClustering(connectivity=knn_graph,n_clusters=30)

In [12]:
h_cluster = h_clustering.fit_predict(X)

In [19]:
h_clustering.labels_.shape

(183204,)

In [20]:
np.bincount(h_clustering.labels_)

array([ 3926, 22013,  8381,    39,  4672,  1817,  6866,   219, 10227,
        1832, 15173, 17741,    95,  3701,     9, 10684, 14752, 15104,
         598,  8591,   286,  2060,  8863,    75,   492,  5632,  9524,
        7498,     2,  2332])

In [21]:
h_clustering.n_leaves_

183204

In [22]:
h_clustering.n_components_ 

1

In [25]:
h_clustering.children_

array([[    85,     87],
       [    86,     88],
       [    89,     91],
       ..., 
       [366401, 366402],
       [366400, 366403],
       [366404, 366405]])

In [46]:
h_clustering.children_.shape

(183203, 2)

In [47]:
h_clustering.get_params()

{'affinity': 'euclidean',
 'compute_full_tree': 'auto',
 'connectivity': <183204x183204 sparse matrix of type '<type 'numpy.float64'>'
 	with 5496120 stored elements in Compressed Sparse Row format>,
 'linkage': 'ward',
 'memory': Memory(cachedir=None),
 'n_clusters': 30,
 'n_components': None,
 'pooling_func': <function numpy.core.fromnumeric.mean>}

In [49]:
all(h_cluster == h_clustering.labels_)

True